### ISSUE TITLE
Random errors when accessing minidlna from Raspbian

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-dleyna#17]
This doesn't seem to occur on Ubuntu (64 bit):

```
2015-08-11 18:57:10,598 ERROR [17654:Core-17] mopidy.core.library: dLeynaBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_dleyna/library.py", line 215, in browse
    for obj in container.ListChildren(0, 0, BROWSE_FILTER):
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.InvalidArgs: Type of message, '(iias)', does not match expected type '(uuas)'
```

**Comment by tkem** [comment]
Wrapping `limit` and `offset` with a `dbus.UInt32` seems to fix this...
