### ISSUE TITLE
un-handled exception from dLeynaBackend

### ISSUE THREAD

**Issue by K-Quadrat** [tkem/mopidy-dleyna#30]
/var/log/mopidy/mopidy.log

ERROR [4261:MainThread] mopidy.commands: Got un-handled exception from dLeynaBackend
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 239, in _actor_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 380, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 94, in start
    obj = cls(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_dleyna/backend.py", line 37, in __init__
    self.dleyna = dLeynaClient(str(env[DBUS_SESSION_BUS_ADDRESS]))
  File "/usr/local/lib/python2.7/dist-packages/mopidy_dleyna/dleyna.py", line 51, in **init**
    self.**future = self.__get_servers()  # TODO: rename
  File "/usr/local/lib/python2.7/dist-packages/mopidy_dleyna/dleyna.py", line 145, in __get_servers
    self.__bus.get_object(SERVER_BUS_NAME, SERVER_ROOT_PATH).GetServers(
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.intel.dleyna-server was not provided by any .service files

**Comment by tkem** [comment]
Did you install `dleyna-server`?

**Comment by K-Quadrat** [comment]
oh thats it, thanks!

**Comment by tkem** [comment]
The error message could be improved though. So reopening this.

**Comment by K-Quadrat** [comment]
Okay i did :)
That the dleyna-server is necessary should be written somewhere.

**Comment by tkem** [comment]
https://github.com/tkem/mopidy-dleyna#dependencies

**Comment by K-Quadrat** [comment]
I checked this file so many times, you've just added the information?! I'm kidding, don't know, too tired yesterday!

A bit off topic but do you know how to run dleyna-renderer?

**Comment by tkem** [comment]
@K-Quadrat: In Mopidy-dLeyna v1.0.2, the mopidy.log would contain:

```
ERROR    Error starting Mopidy-dLeyna: org.freedesktop.DBus.Error.ServiceUnknown: The name com.intel.dleyna-server was not provided by any .service files
ERROR    Got un-handled exception from dLeynaBackend
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 239, in _actor_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 380, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 94, in start
    obj = cls(*args, **kwargs)
  File "/home/tkemmer/src/mopidy-dleyna/mopidy_dleyna/backend.py", line 42, in __init__
    raise exceptions.ExtensionError('Error starting dLeyna client')
ExtensionError: Error starting dLeyna client
```

Maybe still not optimal, but better than that "stack trace from hell", IMHO.
