### ISSUE TITLE
Unhandled exception if DLNA server is disconnected

### ISSUE THREAD

**Issue by ismailof** [tkem/mopidy-dleyna#39]
Hi, 

I've found that disconnecting the DLNA server while still having tracks the playback/tracklist will raise a LookupError to mopidy core. I think that this might be handled in a more controlled way.

The consequence is that the playback doesn't behave as it should with a non-playable track (like trying to play next track)

```
2016-01-17 23:41:40,518 INFO [7917:dLeynaBackend-5] mopidy_dleyna.library: Refreshing dLeyna library
2016-01-18 00:00:49,425 INFO [7917:MainThread] mopidy_dleyna.client: Lost digital media server Kodi [uuid:65500de0-58ec-3c5d-9ff4-6f4844cf636b]
2016-01-18 00:01:34,920 INFO [7917:dLeynaBackend-5] mopidy_dleyna.library: Refreshing dLeyna library
2016-01-18 00:02:58,688 ERROR [7917:Core-19] pykka: Unhandled exception in Core (urn:uuid:ff4b7b7d-652a-4c6d-8aff-4e247f447a74):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/listener.py", line 54, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/actor.py", line 87, in reached_end_of_stream
    self.playback._on_end_of_track()
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 232, in _on_end_of_track
    self._change_track(next_tl_track)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 208, in _change_track
    self._play(on_error_step=on_error_step)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 348, in _play
    backend.playback.change_track(tl_track.track).get() and
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/backend.py", line 245, in change_track
    uri = self.translate_uri(track.uri)
  File "/usr/lib/python2.7/dist-packages/mopidy_dleyna/playback.py", line 11, in translate_uri
    future = dleyna.properties(uri, dleyna.MEDIA_ITEM_IFACE)
  File "/usr/lib/python2.7/dist-packages/mopidy_dleyna/client.py", line 174, in properties
    baseuri, objpath = self.__parseuri(uri)
  File "/usr/lib/python2.7/dist-packages/mopidy_dleyna/client.py", line 217, in __parseuri
    raise LookupError('Cannot resolve %s' % uri)
LookupError: Cannot resolve dleyna://uuid%3a65500de0-58ec-3c5d-9ff4-6f4844cf636b/6d7573696364623a2f2f736f6e67732f3736362e6d7033
```

**Comment by tkem** [comment]
Thanks for reporting! I'm usually not a big fan of "hiding" exceptions in backends, but in this case I agree. Exceptions in `PlaybackProvider.translate_uri()` _should_ be handled in the backend and `None` should be returned, as specified in http://mopidy.readthedocs.org/en/latest/api/backend/#mopidy.backend.PlaybackProvider.translate_uri
