### ISSUE TITLE
Plex DLNA crashes dleyna

### ISSUE THREAD

**Issue by ghost** [tkem/mopidy-dleyna#59]
I'm using mopidy-dleyna for the first time. Neither of my Plex servers show up in Mopidy, and I'm seeing the following error trying to get my Plex servers to show up in Mopidy. I'm seeing an exception in `mopidy.log`. It seems to happen when I click on "Digital Media Servers" in Mopidy. I noticed the access denied error, is that referring to accessing Plex?

```
2017-04-08 03:18:58,526 ERROR [32757:MainThread] dbus.proxies: Introspect error on :1.1:/com/intel/dLeynaServer/server/0: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2017-04-08 03:18:58,574 ERROR [32757:MainThread] dbus.proxies: Introspect error on :1.1:/com/intel/dLeynaServer/server/0: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2017-04-08 03:18:58,986 INFO [32757:MainThread] mopidy_dleyna.client: Found digital media server Plex Media Server: Aurorabox [uuid:e96058cd-e8b1-a2e5-b54a-2e39baa9cf3f]
2017-04-08 03:18:59,021 WARNING [32757:MainThread] mopidy_dleyna.client: Cannot access media server /com/intel/dLeynaServer/server/1: com.intel.dleyna.OperationFailed: Browse operation failed: Access denied
2017-04-08 03:18:59,034 INFO [32757:MainThread] mopidy_dleyna.client: Found digital media server Plex Media Server: Poincare [uuid:1aa02afe-e0f9-ce91-3200-7d13ada2882a]
2017-04-08 03:19:20,207 ERROR [32757:Core-9] mopidy.core.library: dLeynaBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_dleyna/library.py", line 89, in browse
    refs = sorted(self.__servers, key=operator.attrgetter('name'))
  File "/usr/lib/python2.7/dist-packages/mopidy_dleyna/library.py", line 213, in __servers
    name = server.get('FriendlyName', server['DisplayName'])
KeyError: u'DisplayName'
```

**Comment by tkem** [comment]
AFAICS, at least one of your DLNA servers does not provide the DisplayName property, which is mandatory IIRC. I don't know about Plex, but maybe there's a configuration option you need to set for this.
The Access Denied error is most likely related to a Windows machine on your local network. By default, Windows won't allow access via DLNA. If you want to enable this, you can find plenty of instructions on the net.

**Comment by ghost** [comment]
Yes, the access denied is probably the sole Windows machine on my network. Apparently, there are some DLNA client preferences in Plex I'll have to take a look at.

**Comment by tkem** [comment]
I also found this:
https://forums.plex.tv/discussion/73702/writing-profiles-for-dlna-devices
and it looks like Plex indeed does not provide a DisplayName property, but only FriendlyName. I'll have to re-check the DLNA specs, but I guess I could make the name checking less strict in this regard.

**Comment by tkem** [comment]
If you're prepared to do some hacking yourself, you may want to remove the DisplayName access, i.e. change   "/usr/lib/python2.7/dist-packages/mopidy_dleyna/library.py", line 213 to

name = server.get('FriendlyName')

**Comment by ghost** [comment]
I made that change and Plex shows up now! I'll have to do some digging through the logs, because I'm not able to browse the DLNA server yet. This is progress, though. Thanks.

**Comment by ghost** [comment]
Seeing some errors related to DisplayName in ` mopidy.log`: 

```2017-04-08 13:50:37,705 ERROR [20546:Core-9] mopidy.core.library: dLeynaBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_dleyna/library.py", line 91, in browse
    refs = self.__browse(uri)
  File "/usr/lib/python2.7/dist-packages/mopidy_dleyna/library.py", line 161, in __browse
    order = BROWSE_ORDER[translator.ref(obj).type]
  File "/usr/lib/python2.7/dist-packages/mopidy_dleyna/translator.py", line 75, in ref
    return translate(name=obj['DisplayName'], uri=obj['URI'])
KeyError: u'DisplayName'
```

**Comment by tkem** [comment]
I see. Not having a 'DisplayName' breaks some basic assumptions in mopidy-dleyna, so I'm afraid that path leads us nowhere. IIRC there's also a dedicated mopidy-plex backend, maybe you'd rather try that instead.

**Comment by tkem** [comment]
BTW, I guess it's possible to access your Plex server using other DLNA clients, like your Windows machine, for example?

**Comment by tkem** [comment]
Besides the Mopidy logs, you might also want to check your `/var/log/syslog` for any `dleyna-server` related issues.

**Comment by tkem** [comment]
Seems like it's Plex DLNA support that is broken here. Closing this.
