### ISSUE TITLE
Browse broken with BubbleUPnP media server

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-dleyna#63]
Browsing the root collection of BubbleUPnP results in an error with v1.2.1:

```
DEBUG    2018-05-08 22:14:12,301 [16778:dLeynaBackend-9] mopidy_dleyna.util
  Calling D-Bus method ListChildrenEx(dbus.UInt32(0L), dbus.UInt32(500L), [u'DisplayName', u'Type', u'TypeEx', u'Path', u'RefPath'], u'')
DEBUG    2018-05-08 22:14:12,368 [16778:MainThread] mopidy_dleyna.util
  ListChildrenEx reply after 0.066s
DEBUG    2018-05-08 22:14:12,369 [16778:dLeynaBackend-9] mopidy_dleyna.util
  Calling D-Bus method ListChildrenEx(dbus.UInt32(8L), dbus.UInt32(500L), [u'DisplayName', u'Type', u'TypeEx', u'Path', u'RefPath'], u'')
DEBUG    2018-05-08 22:14:12,431 [16778:MainThread] mopidy_dleyna.util
  ListChildrenEx error after 0.062s
ERROR    2018-05-08 22:14:12,432 [16778:Core-10] mopidy.core.library
  dLeynaBackend backend caused an exception.
Traceback (most recent call last):
  File "/home/tkem/.local/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/home/tkem/.local/lib/python2.7/site-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/home/tkem/.local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/home/tkem/.local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/home/tkem/.local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/home/tkem/.local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/home/tkem/src/mopidy-dleyna/mopidy_dleyna/library.py", line 92, in browse
    return list(refs)
  File "/home/tkem/src/mopidy-dleyna/mopidy_dleyna/library.py", line 57, in iterate
    objs, more = future.get()
  File "/home/tkem/.local/lib/python2.7/site-packages/pykka/threading.py", line 44, in get
    return super(ThreadingFuture, self).get(timeout=timeout)
  File "/home/tkem/.local/lib/python2.7/site-packages/pykka/future.py", line 64, in get
    return self._get_hook(timeout)
  File "/home/tkem/src/mopidy-dleyna/mopidy_dleyna/util.py", line 18, in <lambda>
    future.set_get_hook(lambda timeout: func(self.get(timeout)))
  File "/home/tkem/.local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/home/tkem/.local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "<string>", line 1, in <module>
DBusException: com.intel.dleyna.OperationFailed: Unable to parse results of browse: Empty 'DIDL-Lite' node in the DIDL-Lite XML:
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sec="http://www.sec.co.kr/"/>
DEBUG    2018-05-08 22:14:12,434 [16778:MpdSession-14] mopidy.mpd.session
  Response to [::ffff:127.0.0.1]:34712: OK
DEBUG    2018-05-08 22:14:12,435 [16778:MpdSession-14] mopidy.internal.network
  Client most likely disconnected.
DEBUG    2018-05-08 22:14:12,436 [16778:MpdSession-14] mopidy.internal.network
  Already stopping: Actor is shutting down.
```
Note that there's no problem with MiniDLNA.

**Comment by tkem** [comment]
Seems to be a side effect of #51 (so Mopidy-dLeyna v1.2.0 does not have this issue):
Apparently some media servers do not like _at all_ if the browse `offset` is larger than the total number of available items...
