### ISSUE TITLE
Exception from modipy_dleyna in modipy log

### ISSUE THREAD

**Issue by OpeItcLoc03** [tkem/mopidy-dleyna#67]
INFO     [dLeynaBackend-10] mopidy_dleyna.library Refreshing dLeyna library
ERROR    [Core-13] mopidy.core.library dLeynaBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling

  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 114, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3/dist-packages/mopidy_dleyna/library.py", line 88, in browse
    refs = sorted(self.__servers, key=operator.attrgetter("name"))
  File "/usr/lib/python3/dist-packages/mopidy_dleyna/library.py", line 211, in __servers
    name = server.get("FriendlyName", server["DisplayName"])
KeyError: 'DisplayName'

Mopidy-dLeyna: 2.0.0 from /usr/lib/python3/dist-packages

**Comment by tkem** [comment]
Is that a PLEX server on your network?

**Comment by tkem** [comment]
This should be fixed in Mopidy-dLeyna v2.0.1.
